const mongoose = require("mongoose");

const commissionSchema = new mongoose.Schema({
  salesCommission: {
    type: Number,
    default: 0,
  },
  salesTarget: { 
    type: Number, 
    default: 0 
  },
  subscriptionCommission: { 
    type: Number, 
    default: 0 
  },
  salesmanSalesCommissionForManager: {  // New field
    type: Number,
    default: 0,
    description: "Commission percentage manager gets from sales generated by salesmen"
  },
  updatedAt: {
    type: Date,
    default: Date.now,
  },
}, {
  timestamps: true, // This will automatically add createdAt and updatedAt fields
  toJSON: { virtuals: true },
  toObject: { virtuals: true }
});

// Add index for better query performance
// commissionSchema.index({ updatedAt: -1 });

module.exports = mongoose.model("ManagerCommissionSettings", commissionSchema);